version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'cms'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'cms'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Cms123456!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    command:
      --init-file /tmp/create.sql
    volumes:
      - ./create.sql:/tmp/create.sql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '8081:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
  web:
    image: php:8.1-apache
    volumes:
      - .:/var/www/html
      - ./.env.example:/var/www/html/.env
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    command: bash -c "apt-get update && docker-php-ext-install mysqli && docker-php-ext-install pdo_mysql && php artisan key:generate && php artisan migrate:fresh --seed && php artisan passport:install && chmod -R ../html && a2enmod rewrite && service apache2 restart && tail -f /dev/null"
    ports:
      - "8080:80"
    expose:
      - "80"

