version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'cms'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'cms'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Cms123456!'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    command:
      --init-file /tmp/create.sql
    volumes:
      - ./create.sql:/tmp/create.sql
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '8085:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
  web:
    image: php:8.1-apache
    command: 
      - /bin/bash -c 'chmod 777 -R /var/www/html'
    volumes:
      - .:/var/www/html
    ports:
      - "4500:80"
    expose:
      - "80"

